#!/bin/bash

prefix=$1
newTodo="$prefix/.todo.new"
comp="$prefix/.complete"
todo="$prefix/todo"

state="empty"

: > "$newTodo"

while read -r line; do
  if [[ "$state" == "empty" ]]; then
    state="complete"
  fi

  if [[ "$state" == "complete" ]]; then
    if [[ "$line" =~ ^[[:space:]]*$ ]]; then
      echo "$line" >> "$comp"
    else
      state="todo"
      echo "$line" | tee -a "$comp" | xargs -0 printf '✓ %s' 
    fi
  else
    echo "$line" >> "$newTodo"
  fi
done < "$todo"

if [[ "$state" != "todo" ]]; then
  echo "Nothing to complete."
fi

mv -f "$newTodo" "$todo"
