#!/bin/bash

class=$1
state="empty"

: > "$class/todo.new"

while read -r line; do
  if [[ "$state" == "empty" ]]; then
    state="complete"
  fi

  if [[ "$state" == "complete" ]]; then
    if [[ "$line" =~ ^[[:space:]]*$ ]]; then
      echo "$line" >> "$class/complete"
    else
      state="todo"
      echo "$line" | tee -a "$class/complete" | xargs -0 printf '✓ %s' 
    fi
  else
    echo "$line" >> "$class/todo.new"
  fi
done < "$class/todo"

if [[ "$state" == "empty" ]]; then
  echo "Nothing to complete."
  rm "$class/todo.new"
elif [[ "$state" == "complete" ]]; then
  echo "Nothing to complete."
  mv -f "$class/todo.new" "$class/todo"
else
  mv -f "$class/todo.new" "$class/todo"
fi
