#!/bin/bash

if [ "$#" -eq 0 ]; then 
    things=( $(echo ./*/) ) 
else
    things=( $@ )
fi

for thing in ${things[*]}; do
    count=0
    printf "\n---+%s\n" "$thing"

    while read -r line; do
        if [ $count -lt 10 ]
        then
            echo "   | $line"
            (( count += 1 ))
        else
            echo "   | ..."
            break
        fi
    done < "$thing/todo"
done 2> /dev/null

echo


