#!/bin/bash

DEFAULT_IFS="$IFS"
IFS=""

for thing in "$@"; do
    count=0
    echo
    echo ---+"$thing"

    while read -r line; do
        if [ $count -lt 10 ]
        then
            echo "   | $line"
            (( count += 1 ))
        else
            echo "   | ..."
            break
        fi
    done < "$thing/todo"
done 2> /dev/null

IFS="$DEFAULT_IFS"

echo


