#!/bin/bash

cols=$(tput cols)

if [ "$#" -eq 0 ]; then 
    things=( $(echo ./*/) ) 
else
    things=( $@ )
fi

for thing in ${things[*]}; do
    count=0
    printf "\n---+%s\n" "$thing"
    fold -s -w $((cols - 5)) "$thing/todo" | while read -r line; do
        if [ $count -lt 6 ]
        then
            echo "   | $line"
            (( count += 1 ))
        else
            echo "   | ..."
            break
        fi
    # done < "$thing/todo"
    done
  done 2> /dev/null

echo


